module:
  block: 0
  breakpoint: 0
  config: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  image: 0
  link: 0
  menu_link_content: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  state_machine: 0
  system: 0
  telephone: 0
  text: 0
  toolbar: 0
  user: 0
  views: 0
  views_ui: 0
  minimal: 1000
theme:
  stark: 0
  stable: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
